version: '2.2'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - gst-tracker-network
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    env_file:
      - .env

networks:
  gst-tracker-network:

volumes:
  grafana-storage: